# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.PositiveIntegerField()),
                ('volume', models.PositiveIntegerField()),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('date_de_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[(b'M', b'Masculin'), (b'F', b'Feminin')], max_length=1)),
                ('telephone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to=b'static/user/uploads/%Y/%m/%d/')),
            ],
        ),
    ]
