# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170807_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colis',
            old_name='volum',
            new_name='volume',
        ),
    ]
