# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Colis')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Colis')),
                ('id_profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu_depart', models.CharField(max_length=255)),
                ('lieu_arrivee', models.CharField(max_length=255)),
                ('capacite', models.PositiveIntegerField()),
                ('dispo_recup', models.SmallIntegerField()),
                ('date_depart', models.DateField()),
                ('date_arrivee', models.DateField()),
                ('id_profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
