# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_evoi_transporte_voyage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evoi',
            new_name='Envoi',
        ),
    ]
