# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170807_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='defautl_value', max_length=25),
            preserve_default=False,
        ),
    ]
